# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  # boxes at https://atlas.hashicorp.com/search.
   config.vm.box = "bento/ubuntu-16.04"

config.vm.define "app01" do |app01|
    # config.vm.box_check_update = false
     config.vm.network "forwarded_port", guest: 6060, host: 6060
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    app01.vm.network "public_network" , bridge: "eth0"

      # config.vm.synced_folder "../data", "/vagrant_data"
      # Provider-specific configuration so you can fine-tune various
      # backing providers for Vagrant. These expose provider-specific options.
      # Example for VirtualBox:
      #
      app01.vm.provider "virtualbox" do |vb|
      #  vb.gui = true
        vb.memory = "2024"
        vb.cpus = 4
      end

      app01.vm.provision "ansible",run: "always"   do |ansible| 
        ansible.sudo = true
        ansible.playbook = "playbook.yml"
      end
  end
end