var message = `
MMMMMMMM               MMMMMMMM                              TTTTTTTTTTTTTTTTTTTTTTT                                                             BBBBBBBBBBBBBBBBB                                     tttt                                               
M:::::::M             M:::::::M                              T:::::::::::::::::::::T                                                             B::::::::::::::::B                                 ttt:::t                                               
M::::::::M           M::::::::M                              T:::::::::::::::::::::T                                                             B::::::BBBBBB:::::B                                t:::::t                                               
M:::::::::M         M:::::::::M                              T:::::TT:::::::TT:::::T                                                             BB:::::B     B:::::B                               t:::::t                                               
M::::::::::M       M::::::::::Myyyyyyy           yyyyyyy     TTTTTT  T:::::T  TTTTTTwwwwwww           wwwww           wwwwwww ooooooooooo          B::::B     B:::::Byyyyyyy           yyyyyyyttttttt:::::ttttttt        eeeeeeeeeeee        ssssssssss   
M:::::::::::M     M:::::::::::M y:::::y         y:::::y              T:::::T         w:::::w         w:::::w         w:::::woo:::::::::::oo        B::::B     B:::::B y:::::y         y:::::y t:::::::::::::::::t      ee::::::::::::ee    ss::::::::::s  
M:::::::M::::M   M::::M:::::::M  y:::::y       y:::::y               T:::::T          w:::::w       w:::::::w       w:::::wo:::::::::::::::o       B::::BBBBBB:::::B   y:::::y       y:::::y  t:::::::::::::::::t     e::::::eeeee:::::eess:::::::::::::s 
M::::::M M::::M M::::M M::::::M   y:::::y     y:::::y                T:::::T           w:::::w     w:::::::::w     w:::::w o:::::ooooo:::::o       B:::::::::::::BB     y:::::y     y:::::y   tttttt:::::::tttttt    e::::::e     e:::::es::::::ssss:::::s
M::::::M  M::::M::::M  M::::::M    y:::::y   y:::::y                 T:::::T            w:::::w   w:::::w:::::w   w:::::w  o::::o     o::::o       B::::BBBBBB:::::B     y:::::y   y:::::y          t:::::t          e:::::::eeeee::::::e s:::::s  ssssss 
M::::::M   M:::::::M   M::::::M     y:::::y y:::::y                  T:::::T             w:::::w w:::::w w:::::w w:::::w   o::::o     o::::o       B::::B     B:::::B     y:::::y y:::::y           t:::::t          e:::::::::::::::::e    s::::::s      
M::::::M    M:::::M    M::::::M      y:::::y:::::y                   T:::::T              w:::::w:::::w   w:::::w:::::w    o::::o     o::::o       B::::B     B:::::B      y:::::y:::::y            t:::::t          e::::::eeeeeeeeeee        s::::::s   
M::::::M     MMMMM     M::::::M       y:::::::::y                    T:::::T               w:::::::::w     w:::::::::w     o::::o     o::::o       B::::B     B:::::B       y:::::::::y             t:::::t    tttttte:::::::e           ssssss   s:::::s 
M::::::M               M::::::M        y:::::::y                   TT:::::::TT              w:::::::w       w:::::::w      o:::::ooooo:::::o     BB:::::BBBBBB::::::B        y:::::::y              t::::::tttt:::::te::::::::e          s:::::ssss::::::s
M::::::M               M::::::M         y:::::y                    T:::::::::T               w:::::w         w:::::w       o:::::::::::::::o     B:::::::::::::::::B          y:::::y               tt::::::::::::::t e::::::::eeeeeeee  s::::::::::::::s 
M::::::M               M::::::M        y:::::y                     T:::::::::T                w:::w           w:::w         oo:::::::::::oo      B::::::::::::::::B          y:::::y                  tt:::::::::::tt  ee:::::::::::::e   s:::::::::::ss  
MMMMMMMM               MMMMMMMM       y:::::y                      TTTTTTTTTTT                 www             www            ooooooooooo        BBBBBBBBBBBBBBBBB          y:::::y                     ttttttttttt      eeeeeeeeeeeeee    sssssssssss    
                                     y:::::y                                                                                                                               y:::::y                                                                        
                                    y:::::y                                                                                                                               y:::::y                                                                         
                                   y:::::y                                                                                                                               y:::::y                                                                          
                                  y:::::y                                                                                                                               y:::::y                                                                           
                                 yyyyyyy                                                                                                                               yyyyyyy                                                                            
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                          
`;




console.log(message);